export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_USERNAME = "GET_USERNAME";

export const USER_INFO_RETRIEVE_REQUESTED = "USER_INFO_RETRIEVE_REQUESTED";
export const USER_INFO_RETRIEVE_SUCCEEDED = "USER_INFO_RETRIEVE_SUCCEEDED";
export const USER_INFO_RETRIEVE_FAILED = "USER_INFO_RETRIEVE_FAILED";
